
name: Flask CI/CD

on:
  push:
    branches:
      - ft/*
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install flask

      # Step 4: Run Flask app test (starts server for check)
      - name: Run Flask app
        run: |
          python app.py &
          sleep 5
          curl -I http://127.0.0.1:5000

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-flask-ci .

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name flask-app python-flask-ci
          sleep 5
          curl -I http://127.0.0.1:5000



